package octii.app.taxiapp.constants.sockets

enum class MessageType {
    ORDER_REJECT, ORDER_REQUEST, ORDER_ACCEPT, ORDER_FINISHED,
    NO_ORDERS, TAXIMETER_UPDATE, COORDINATES_UPDATE, TAXIMETER_START
}