package octii.app.taxiapp.constants

class StaticTaximeter {
	companion object {
		const val SHARED_PREFERENCES_TAXIMETER = "TAXIMETER PREFERENCES"
		const val TAXIMETER_INTENT_FILTER = "octii.app.taxiapp.TAXIMTER_FILTER"
		const val TAXIMETER_BUNDLE_TIME = "time"
		const val TAXIMETER_BUNDLE_WAINTING_TIME = "waiting"
		const val SHARED_PREFERENCES_TIMER_STATUS = "TIMER_STATUS"
		const val SHARED_PREFERENCES_UPDATING_COORDINATES = "UPDATING_COORDINATES"
		const val TAXIMETER_STATUS = "TAXIMETER_STATUS"
		const val TAXIMETER_STATUS_INTENT_FILTER = "octii.app.taxiapp.TAXIMETER_STATUS_INTENT_FILTER"
		const val TAXIMETER_DESTROY_DATE = "TAXIMETER_DESTROY_DATE"
	}
}